-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 24 авг 2016 в 22:32
-- Версия на сървъра: 10.1.8-MariaDB
-- PHP Version: 7.0.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `teamwork`
--

-- --------------------------------------------------------

--
-- Структура на таблица `dangers`
--

CREATE TABLE `dangers` (
  `id` int(11) NOT NULL,
  `image` varchar(150) NOT NULL,
  `header` varchar(50) NOT NULL,
  `text` longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Схема на данните от таблица `dangers`
--

INSERT INTO `dangers` (`id`, `image`, `header`, `text`) VALUES
(1, 'http://static.srcdn.com/wp-content/uploads/Locating-a-Gym-in-Pokemon-GO.jpg', '1. RELIGIOUS HATE SPEECH', 'As Pokemon GO uses notable public structures as gyms for players to train at, a lot of churches are seeing more foot traffic than usual. Plenty of players have joked online at the strange behavior that the game is encouraging, as gamers visit religious sites en masse as part of their Pokemon pilgrimage.\r\nWhile in most cases these establishments are taking their newfound popularity among Pokemon fans in their stride, some churches have found opportunistic ways of spreading their message through Pokemon. Most notably, the Westboro Baptist Church, infamous for their outspoken condemnation of many aspects of modern life, has found a way to capitalize on its newfound status as a Pokemon gym.\r\nAfter an enterprising player of the game established themselves as the gym leader for the Westboro Baptist Church, using a pink Clefairy named ''LOVEISLOVE'', the church has responded online by filling its social media presence with a collection of Pokemon-themed memes denouncing its gym leader in an attempt to spread hatespeech. It''s likely that this is the first of many religious incidents surrounding the game as players spend more time near places of worship for various faiths.'),
(2, 'http://static.srcdn.com/wp-content/uploads/Winning-a-Battle-at-a-Los-Angeles-Pokemon-Gym.jpg', '2. TRESPASSING CHARGES', 'Stores, restaurants, and other establishments across the world have been seeing a large influx of visitors, many of whom aren''t actually looking to buy anything. One Dairy Queen is reported to have put up a sign stating that its rare Pokemon are for patrons only, and it''s likely that as Pokemania continues to spread, many establishments will be increasingly frustrated with players loitering in entranceways or scaring away business.\r\n\r\nNot all places of significance in Pokemon GO are even open to the public - many gamers have been scaling fences and sneaking onto private property in order to get their hands on rare creatures, and it''s only a matter of time before such antics end badly.\r\n\r\nIn all cases, players should try to be conscious of the effects their behavior have on others. One man, who lives in a converted church, has discovered a steady stream of players loitering outside his house to play. While he''s been very relaxed and welcoming to players, there''s no guarantee that every gym owner will be as welcoming.'),
(3, 'http://static.srcdn.com/wp-content/uploads/Wartortle-in-Pokemon-GO.jpg', '3. DATA CHARGES', 'Pokemon GO uses a lot of mobile data. It has to, really - after all, the game spends a lot of time using map data to generate various location information and to help keep track of where the player is in relation to rare Pokemon in the area.\r\n\r\nNot everyone, however, has an expansive data package for their smartphone - certainly not enough to keep up with a lot of playing. Plenty of distraught players have taken to Twitter to vent their frustration at not being able to catch ''em all because they simply don''t have enough mobile data to do so. Other players are in an even more dangerous situation: potentially accruing large charges for using more data than they have as part of their plan, or getting hit with data roaming charges while attempting to play on vacation.\r\n\r\nThankfully, there are tricks to reducing the amount of data that the game uses, such as pre-downloading maps of local areas so that the game isn''t constantly refreshing them while out and about, or simply connecting to Wi-Fi when it''s available.'),
(4, 'http://static.srcdn.com/wp-content/uploads/Finding-a-Psyduck-in-Pokemon-GO.jpg', '4. SORE LEGS', 'Pokemon GO is a great incentive for many players to live a more active lifestyle - as a game that requires as much as 10km of walking before players can hatch certain eggs and find key Pokemon, the game is helping to get a lot of players up off the couch as they discover the digital rewards of exercise.\r\n\r\nThat said, players who aren''t used to a large amount of exercise should be careful not to overdo things. Plenty of previously sedentary Pokemon players have reported sore legs and other conditions caused by moving around far more than they usually would, either by bike or on foot.\r\n\r\nWhile these conditions are hardly life-threatening, and while the exercise is definitely going to have long-term benefits after a while, players who aren''t used to high levels of physical exertion should be careful not to overdo things and leave themselves exhausted, miles away from home.'),
(5, 'http://static.srcdn.com/wp-content/uploads/Playing-Pokemon-GO-in-Public.jpg', '5. UNWANTED ATTENTION', 'Pokemon GO encourages a lot of socially acceptable behavior - plenty of players are making new friends as they battle other gamers and share tips on the best local spots to find creatures. Gamers are getting to know other Pokemon fans in their area, and in many cases, Pokemon GO is helping to bring communities closer together.\r\n\r\nUnfortunately, though, not all attention from fellow players in wanted or welcomed. There have been reports of players of the game who have felt uncomfortable with the way some other players have approached them, invading their personal space in what is often likely merely an eagerness for the game, but which has left players feeling vulnerable and awkward.\r\n\r\nNot all players of the game are interested in making new friends, and as much fun as playing Pokemon GO together might be, it''s important for players to respect when someone else would rather play by themselves.'),
(6, 'http://static.srcdn.com/wp-content/uploads/Hatching-an-Egg-in-Pokemon-GO.jpg', '6. PHONE VIRUSES', 'Pokemon GO is not yet available around the entire world - at least not officially. After a very rocky initial release in Australia, New Zealand, and America, Nintendo have opted to put a full worldwide release on hold, meaning that players in various parts of the world are still not able to download the game through legitimate channels.\r\n\r\nSome intrepid players, however, have discovered that while the game isn''t available in the Android Play store in their region, it can be installed manually by downloading the game''s APK from various hosts online. This has let a lot of players across Europe and in other parts of the world gain access to the game earlier than Nintendo would have liked.\r\n\r\nThe problem with this, though, is that not all APKs that are in circulation are legitimate - plenty of Trojan Horse viruses exist, hidden among certain versions of the game, waiting for players to install them and give hackers permission to access all of their important files. Add to this reports of privacy issues for even legitimate downloads, and there''s a potential for serious security risks with the new game.\r\n\r\nSo for any player who''s considering downloading the game ahead of its official release, be warned: some available versions of the game are less than legitimate.'),
(7, 'http://static.srcdn.com/wp-content/uploads/Pokemon-GO-Gameplay1.jpg', '7. WASTING POLICE TIME', 'Pokemon GO assigns real world locations of importance as gyms that players can travel to in order to battle each other and pick up important rare items. Unfortunately for the locations that have been chosen, the extra attention caused by players coming to stock up on Pokeballs isn''t always welcome.\r\n\r\nSuch is the case with a police station in Darwin, Australia - having discovered why so many young people are visiting the station while playing a game on their phone, the police have issued a statement reminding players that they don''t actually have to enter the building in order to register as being in the gym. Apparently, a few too many visitors has meant that the station has been overrun, and the police, while polite about it, aren''t eager to have more players taking up space in the lobby.\r\n\r\nPlayers should take care to make sure that their adventures don''t involve wasting time for local police, no matter how tempting the treasures that await at various stations might be.'),
(8, 'http://static.srcdn.com/wp-content/uploads/Pokemon-GO-Accessory.jpg', '8. DEAD BATTERY', 'By all accounts, Pokemon GO drains phone battery life fast. This is hardly all that surprising - the game makes constant use of the player''s GPS tracking, is regularly connected to the internet, and often uses the phone''s camera to produce augmented reality images of the Pokemon that the player is trying to capture.\r\n\r\nPlayers should take care when exploring the Pokemon world alone - it''s easy to wander into unfamiliar paths while playing, and when a phone battery dies, it''s easy for a player to become stranded in the middle of nowhere without any way to contact assistance.\r\n\r\nPlayers who find their phone batteries dying a lot quicker than they''d like should look into the various tips and tricks that exist to help save battery life, and those who intend to do a lot of playing might want to invest in the game''s (currently unavailable) accessory that tracks the player moments and creates alerts without the need to constantly be checking a phone.'),
(9, 'http://static.srcdn.com/wp-content/uploads/Magikarp-in-Pokemon-GO.jpg', '9. MARITAL ARGUMENTS', 'Playing Pokemon with family members can be an enjoyable experience - it''s an opportunity for families to take time out to go for walks in parks as they explore the world together in search of new monsters to capture. That said, there is definitely a time and a place where playing Pokemon GO is appropriate, and whipping out a phone to play at the wrong time can lead to disastrous consequences for marital harmony.\r\n\r\nTake, for example, the case of the man who found a Pidgey on his wife''s hospital bed while the couple was waiting for a C-section. According to the player, this elicited a few eye-rolls as his wife realized his priorities in that moment, but otherwise he got off lightly.\r\n\r\nIf the comments on the player''s initial Imgur photo are to be believed, however, not every Pokemaniac would receive a similar reaction: many commenters have suggested that the man''s behavior was insensitive, or potentially harmful to a relationship.\r\n\r\nThis being the case, be warned: while many partners might understand or even encourage playing Pokemon GO in unusual circumstances, there''s definitely the potential for marital strife if a Pokemon trainer starts playing at the wrong moment.'),
(10, 'http://static.srcdn.com/wp-content/uploads/Walking-Around-in-Pokemon-GO.jpg', '10. RACE-RELATED ATTACKS', 'While in many cases, the dangers that befall players of Pokemon GO are caused primarily by their own careless or reckless behavior, unfortunately, there are some problems that will only be faced by players based on their race. Omari Akil has called the game "a death sentence if you are a black man," and as awful as the implications of this are, Akil''s comments are certainly a warning that bear repeating for anyone who might be in danger.\r\n\r\nAccording to Akil, the behavior that Pokemon GO encourages, such as walking around in unusual patterns in unfamiliar neighborhoods, may lead residents to believe that young black players of the game are doing something suspicious. Akil argues that there is a ''statistically disproportionate'' chance that the cops might be called, and a similar chance that the player might not be given the benefit of the doubt while reaching into their pocket for their phone or other identification.\r\n\r\nAt the moment, race relations across America are exceptionally tense. While this is a difficult subject to address, it''s vitally important to repeat Akil''s warning: black players of the game should take extra care when exploring the world in search of new Pokemon.'),
(11, 'http://static.srcdn.com/wp-content/uploads/Bike-Riding-in-Pokemon-GO-Trailer.jpg', '11. CAR CRASHES', 'Driving while using a phone is generally understood to be a bad idea. That''s not enough to stop many people from doing so, of course, especially when it comes to catching Pokemon. Driving while playing the game is incredibly convenient - as many of the game''s features measure how far a person has traveled, players can cover more ground at a quicker pace, and can also find key points where Pokemon appear by traveling around faster.\r\n\r\nUnfortunately, though, looking at a smartphone while driving is such a prevalent concern that multiple law enforcement agencies around the world have had to issue warnings to players. These are very warranted, as reports from various players on Twitter have pointed to some very reckless behavior that has led to accidents in many cases.\r\n\r\nIt doesn''t help that the game spawns Pokemon in unhelpful positions - even Penny Arcade''s Mike Krahulik has reported almost getting run over while trying to catch a wild Poliwhirl in the middle of the road.'),
(12, 'http://static.srcdn.com/wp-content/uploads/Locating-a-Gym-in-Pokemon-GO.jpg', '12. JOB LOSS', 'So playing Pokemon GO outside can have potentially dangerous circumstances - that''s fine, though, because the game can still be played indoors without a problem, right? Well, even indoors, it''s important to be careful about how and when you play.\r\n\r\nIn a post on Reddit which has since been deleted, user scarstruck4 explained that, while working for a bank dealing with sensitive information, the player couldn''t help but whip out their phone to try to capture a Zubat which was flying nearby. While scarstruck4''s company allows the use of phones at desks, using the camera is a serious breach of security measures, and as Pokemon GO uses a phone''s camera to create an augmented reality image, scarstruck4''s phone was promptly confiscated and sent for inspection at the company''s head office. In the meantime, scarstruck4 is looking at serious disciplinary action.\r\n\r\nThis isn''t even the only case of Pokemon GO putting people''s careers in jeopardy - a player in Singapore who was caught using colorful language on Facebook to express his annoyance at the game''s implementation in the country, has been fired for indecent conduct on social media. So watch out - there can be serious consequences to playing Pokemon GO, or even talking about it, in the wrong setting!'),
(13, 'http://static.srcdn.com/wp-content/uploads/Pokemon-GO-on-an-iPhone.jpg', '13. DEAD BODIES', 'Exploring the woods and fields in the countryside looking for Pokemon might seem like a good way to avoid the dangers of inner-city robberies, but there are dangers hiding everywhere, and for one gamer, Pokemon GO led to a pretty traumatic experience.\r\n\r\nThe nineteen-year-old player in Wyoming was exploring the countryside near her home, looking for rare creatures. After hopping a fence to get to one particularly exciting capture, she was exploring a natural water source when she came across a dead body.\r\n\r\nAccording to the local police, it appears that no foul play was involved and that the man who had been found had accidentally drowned - even so, finding a dead body is a fairly traumatic experience for any player of the game.\r\n\r\nAs Pokemon GO continues to rise in popularity and players explore further and wider in their search for new Pokemon, it''s likely that more similar stories will crop up. Players should be wary of dangerous situations and do their best to keep a safe distance from anything that looks unusual.'),
(14, 'http://static.srcdn.com/wp-content/uploads/Gengar-in-Pokemon-GO.jpg', '14. MUGGINGS', 'If players don''t fall afoul of potholes, ditches, or other natural dangers in the landscape around them, there''s also the risk of potential muggings. Pokemon GO works by spawning certain Pokemon and items at specific locations, meaning that lots of players will find the same rare creatures in the same spots. It didn''t take long after the release of the game for muggers to realize how this could be exploited.\r\n\r\nJust a few days after the release of the game, police on O''Fallon, Missouri got a call at 2am about a group of four teens who were parked on a Pokemon hotspot - according to reports, when players of the game stumbled into the parking lot that the teens were hiding in, they''d exit the car and rob gamers at gunpoint.\r\n\r\nTake this as a warning: as much fun as Pokemon GO might be, it''s not necessarily safe to walk around in secluded areas with your smartphone out in front of you - pay attention to your surroundings and go in groups to minimize risks.'),
(15, 'http://static.srcdn.com/wp-content/uploads/Pokemon-Battle-in-Pokemon-GO.jpg', '15. INJURIES', 'It didn''t take long after Pokemon GO''s release for the first reports of injuries to come flooding in. Players reported falling over pot holes, twisting ankles, and even walking into lampposts and other obstacles as they spent their time engrossed in their phones without paying full attention to their surroundings.\r\n\r\nFor example, Redditor Amalthea took to the site to explain how, just thirty minutes after downloading the game, they had managed to slip and fall into a ditch, fracturing one of the bones in their foot. Amalthea is looking at 6-8 weeks of recovery after telling doctors at the ER that they were out walking their dog.\r\n\r\nThe problems of Pokemon GO are compounded thanks to the number of players who are heading out to catch Pokemon at night: so if you''re planning to explore the world around you in search of new creatures to capture, be sure to tread carefully and watch your step.'),
(16, 'http://static.srcdn.com/wp-content/uploads/Pokemon-GO-Logo.jpg', 'CONCLUSION', 'Pokemon GO has a lot of fantastic qualities. It promotes healthy exercise and making friends, and its popularity speaks to the enduring dream of becoming a Pokemon master that''s shared by millions of players across the world.\r\n\r\nThat said, the game is not without its risks. While sore legs and data charges might not be all that scary, there''s a very real threat that the game could lead to disaster and tragedy unless players are careful where and how they play.\r\n\r\nSo the next time a rare Pokemon appears in the middle of the road, be sure to ask yourself whether it''s worth risking a car crash to get hold of it!');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `dangers`
--
ALTER TABLE `dangers`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `dangers`
--
ALTER TABLE `dangers`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
